<?php

use App\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'id'             => 1,
                'name'           => 'Admin',
                'email'          => 'admin@admin.com',
                'password'       => bcrypt('password123'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 2,
                'name'           => 'Ike Fitriyaningsih',
                'email'          => 'ike.fitriyaningsih@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 3,
               'name'           => 'Hernawati S. Samosir',
                'email'          => 'hernawati.samosir@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 4,
               'name'           => 'Monalisa Pasaribu',
                'email'          => 'monalisa.pasaribu@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 5,
               'name'           => 'Goklas Henry Agus Panjaitan',
                'email'          => 'goklas.panjaitan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 6,
               'name'           => 'Tegar Arifin Prasetyo',
                'email'          => 'tegar.prasetyo@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 7,
               'name'           => 'Tiurma Lumban Gaol',
                'email'          => 'tiurma.gaol@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 8,
               'name'           => 'Rudy Chandra',
                'email'          => 'rudy.chandra@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 9,
               'name'           => 'Bella Wahmilyana Asril',
                'email'          => 'bella.asril@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 10,
               'name'           => 'Joyce Rotua Natalia Manurung',
                'email'          => 'joyce.manurung@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 11,
               'name'           => 'Eka Stephani Sinambela',
                'email'          => 'eka.sinambela@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 12,
               'name'           => 'Marojahan Mula Timbul Sigiro',
                'email'          => 'marojahan.sigiro@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 13,
               'name'           => 'Sari Muthia Silalahi',
                'email'          => 'sari.silalahi@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 14,
               'name'           => 'Gerry Italiano Wowiling',
                'email'          => 'gerry.wowiling@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 15,
               'name'           => 'Istas Manalu',
                'email'          => 'istas.manalu@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 16,
               'name'           => 'Frengki Simatupang',
                'email'          => 'frengki.simatupang@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 17,
               'name'           => 'Dr. Arnaldo Marulitua Sinaga',
                'email'          => 'arnaldo.sinaga@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 18,
               'name'           => 'Riyanthi Angrainy Sianturi',
                'email'          => 'riyanthi.sianturi@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 19,
               'name'           => 'Rumondang Miranda Marsaulina',
                'email'          => 'rumondang.marsaulina@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 20,
               'name'           => 'Verawaty Situmorang',
                'email'          => 'verawaty.situmorang@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 21,
               'name'           => 'Regina Ayunita Tarigan',
                'email'          => 'regina.tarigan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 22,
               'name'           => 'Ardiles Sinaga',
                'email'          => 'ardiles.sinaga@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 23,
               'name'           => 'Oppir Hutapea, S.Tr.Kom, M.Kom',
                'email'          => 'oppir.hutapea@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 24,
               'name'           => 'Asyraf Atthariq Putra Gary',
                'email'          => 'asyraf.gary@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 25,
               'name'           => 'Cynthia Deborah Nababan',
                'email'          => 'cynthia.nababan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 26,
               'name'           => 'Ana Muliyana',
                'email'          => 'ana.muliyana@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 27,
               'name'           => 'Dr. Arlinta Christy Barus',
                'email'          => 'arlinta.barus@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 28,
               'name'           => 'Arie Satia Dharma',
                'email'          => 'arie.dharma@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 29,
               'name'           => 'Herimanto',
                'email'          => 'herimanto.herimanto@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 30,
               'name'           => 'Iustisia N. Simbolon',
                'email'          => 'iustisia.simbolon@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 31,
               'name'           => 'Johannes Harungguan',
                'email'          => 'johannes.harungguan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 32,
               'name'           => 'Ranty Deviana Siahaan',
                'email'          => 'ranty.siahaan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 33,
               'name'           => 'Mario Elyezer Subekti Simaremare',
                'email'          => 'mario.simaremare@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 34,
               'name'           => 'Parmonangan Rotua Togatorop',
                'email'          => 'parmonangan.togatorop@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 35,
               'name'           => 'Samuel Indra Gunawan Situmeang',
                'email'          => 'samuel.situmeang@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 36,
               'name'           => 'Rentauli Mariah Silalahi',
                'email'          => 'rentauli.silalahi@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 37,
               'name'           => 'Humasak Tomy Argo Simanjuntak',
                'email'          => 'humasak.simanjuntak@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 38,
               'name'           => 'Rosni Lumbantoruan',
                'email'          => 'rosni.lumbantoruan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 39,
               'name'           => 'Junita Amalia',
                'email'          => 'junita.amalia@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 40,
               'name'           => 'Sarah Rosdiana Tambunan',
                'email'          => 'sarah.tambunan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 41,
               'name'           => 'Susi Eva Maria Purba',
                'email'          => 'susi.purba@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 42,
               'name'           => 'Chandro Pardede',
                'email'          => 'chandro.pardede@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 43,
               'name'           => 'Albert Sagala',
                'email'          => 'albert.sagala@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 44,
               'name'           => 'Tennov Simanjuntak',
                'email'          => 'tennov.simanjuntak@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 45,
               'name'           => 'Good Fried Panggabean',
                'email'          => 'good.panggabean@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 46,
               'name'           => 'Indra Hartarto Tambunan',
                'email'          => 'indra.tambunan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 47,
               'name'           => 'Asido Saragih',
                'email'          => 'asido.saragih@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 48,
               'name'           => 'Guntur Petrus Boy Knight',
                'email'          => 'guntur.knight@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 49,
               'name'           => 'Deni Parlindungan Lumbantoruan',
                'email'          => 'deni.lumbantoruan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 50,
               'name'           => 'Alfriska Oktarina Silalahi',
                'email'          => 'alfriska.silalahi@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 51,
               'name'           => 'Philippians Manurung',
                'email'          => 'philippians.manurung@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 52,
               'name'           => 'Andi Ray Hutauruk',
                'email'          => 'andi.hutauruk@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 53,
               'name'           => 'Mariana Simanjuntak',
                'email'          => 'mariana.simanjuntak@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 54,
               'name'           => 'Josua Boyke William Jawak',
                'email'          => 'josua.jawak@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 55,
               'name'           => 'Fitriani Tupa Ronauli Silalahi',
                'email'          => 'fitriani.silalahi@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 56,
               'name'           => 'Samuel Hasudungan Tampubolon',
                'email'          => 'samuel.tampubolon@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 57,
               'name'           => 'Hadi Sutanto Saragi',
                'email'          => 'hadi.saragi@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 58,
               'name'           => 'Iswanti Sihaloho',
                'email'          => 'iswanti.sihaloho@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 59,
               'name'           => 'Niko Saripson Pandapotan Simamora',
                'email'          => 'niko.s.t.@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 60,
               'name'           => 'Wesly Mailander Siagian',
                'email'          => 'wesly.siagian@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 61,
               'name'           => 'Santi Febri Arianti',
                'email'          => 'santi.arianti@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 62,
               'name'           => 'Aga Nugraha',
                'email'          => 'aga.nugraha@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 63,
               'name'           => 'Muhammad Ilham Maulana',
                'email'          => 'muhammad.maulana@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 64,
               'name'           => 'Batara Parada Siahaan',
                'email'          => 'batara.siahaan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 65,
               'name'           => 'Theodora M Putri',
                'email'          => 'theodora.putri@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 66,
               'name'           => 'Adrianto Prigartantyo',
                'email'          => 'adrianto.prigartantyo@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 67,
               'name'           => 'Astiti Aditia',
                'email'          => 'astiti.aditia@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 68,
               'name'           => 'Dedy Anwar',
                'email'          => 'dedy.anwar@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 69,
               'name'           => 'Merry Meryam Martgrita',
                'email'          => 'merry.martgrita@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 70,
               'name'           => 'Roga Florida Kembaren',
                'email'          => 'dra..m.si@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 71,
               'name'           => 'Ellyas Alga Nainggolan',
                'email'          => 'ellyas.nainggolan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 72,
               'name'           => 'Juli Yanti Damanik',
                'email'          => 'juli.damanik@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 73,
               'name'           => 'Meiyer Marthen Kinda',
                'email'          => 'meiyer.kinda@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 74,
               'name'           => 'Nina Juliana Roberta Turnip',
                'email'          => 'nina.turnip@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 75,
               'name'           => 'Berlian Simanjuntak',
                'email'          => 'berlian.simanjuntak@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 76,
               'name'           => 'Yoli Agnesia',
                'email'          => 'yoli.agnesia@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 77,
               'name'           => 'Yulisa Lestari',
                'email'          => 'yulisa.lestari@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 78,
               'name'           => 'M. Jusli Penus Sagala',
                'email'          => 'jusli.sagala@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 79,
               'name'           => 'Rusdiansyah',
                'email'          => 'rusdiansyah.rusdiansyah@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
             [
                'id'             => 80,
               'name'           => 'Ronald Pasaribu',
                'email'          => 'ronald.pasaribu@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
            [
                'id'             => 81,
               'name'           => 'Mei Pane',
                'email'          => 'mei.pane@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
            [
                'id'             => 82,
               'name'           => 'Sari Nadapnap',
                'email'          => 'sariah.Nadapnap@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
            [
                'id'             => 83,
               'name'           => 'Tantri Harianti Silaen',
                'email'          => 'tantri.silaen@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
            [
                'id'             => 84,
               'name'           => 'Revi Angeli Siahaan',
                'email'          => 'revi.siahaan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
            [
                'id'             => 85,
               'name'           => 'Yessi Sovranita Pangaribuan',
                'email'          => 'yessi.pangaribuan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
                        [
                'id'             => 86,
               'name'           => 'Abdulla Ubaid',
                'email'          => 'abdulla.ubaid@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
                        [
                'id'             => 87,
               'name'           => 'Febrian Cornellius Sidabutar',
                'email'          => 'febrian.sidabutar@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
                        [
                'id'             => 88,
               'name'           => 'Siska Manullang',
                'email'          => 'siska.manullang@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
                        [
                'id'             => 89,
               'name'           => 'Chintya May Pasaribu',
                'email'          => 'chintya.pasaribu@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
                        [
                'id'             => 90,
               'name'           => 'Febri Chatarina Sianipar',
                'email'          => 'febri.sianipar@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
                        [
                'id'             => 91,
               'name'           => 'Elisa Harianja',
                'email'          => 'elisa.harianja@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
            [
                'id'             => 92,
               'name'           => 'Rizal Sahala Bakti',
                'email'          => 'rizal.sahala@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ], 
            [
                'id'             => 93,
               'name'           => 'Sari Feronika Nadapnap',
                'email'          => 'sari.feronika@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 94,
               'name'           => 'Anggiat Tambunan',
                'email'          => 'anggiat.tambunan@del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],  
            [
                'id'             => 95,
               'name'           => 'Darel Deonaldo Aloysius Pinem',
                'email'          => 'ifs19027@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 96,
               'name'           => 'Risky Junior Martua Panggabean',
                'email'          => 'ifs19050@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 97,
               'name'           => 'Kartika Novia Hutauruk',
                'email'          => 'ifs19055@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 98,
               'name'           => 'Lucas Ronaldi Hutabarat',
                'email'          => 'iss19036@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 99,
               'name'           => 'Albert Immanuel Sianipar',
                'email'          => 'els19021@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 100,
               'name'           => 'Jeffrey Jeverson Pasaribu',
                'email'          => 'els19024@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 101,
               'name'           => 'Amiton Wanimbo',
                'email'          => 'if420012@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 102,
               'name'           => 'Rohkid Kogoya',
                'email'          => 'if420020@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 103,
               'name'           => 'Daniel Paskah Totti Limbong',
                'email'          => 'iss20034@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 104,
               'name'           => 'Terecia Deswita Cristanti S',
                'email'          => 'bps20002@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 105,
               'name'           => 'Rizka Arta Rossa Tambun',
                'email'          => 'bps20004@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 106,
               'name'           => 'Wasti Fona Athalia Sidauruk',
                'email'          => 'bps20005@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],

            [
                'id'             => 107,
               'name'           => 'Friskila Ariyanty',
                'email'          => 'bps20020@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],

            [
                'id'             => 108,
               'name'           => 'Heru Jusak Cipto',
                'email'          => 'els20012@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 109,
               'name'           => 'Ita Anjelly P. Sirait',
                'email'          => 'if420051@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 110,
               'name'           => 'Jensri Joice Samosir',
                'email'          => 'if421050@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 111,
               'name'           => 'William Hubertus Pangibulan',
                'email'          => 'if421030@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 112,
               'name'           => 'Viranty Napitupulu',
                'email'         => 'if421055@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 113,
               'name'           => 'Dini H.J. Sipahutar',
                'email'          => 'if421051@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 114,
               'name'           => 'Masnida Octaviana Panjaitan',
                'email'          => 'if421027@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 115,
               'name'           => 'Sri Nengsi Rajagukguk',
                'email'          => 'if421052@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 116,
               'name'           => 'Sopranita Panjaitan',
                'email'          => 'if421012@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 117,
               'name'           => 'Angel Stephanie',
                'email'          => 'if421026@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 118,
               'name'           => 'Ray Anggara Siagian',
                'email'          => 'if421038@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 119,
               'name'           => 'Gilbert Marpaung',
                'email'          => 'if421003@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 120,
               'name'           => 'Grase Thessalonika Panjaitan',
                'email'          => 'ifs21053@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 121,
               'name'           => 'Tiara Yuliandari',
                'email'          => 'ifs21007@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 122,
               'name'           => 'Rio Eka Pasaribu',
                'email'          => 'ifs21033@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 123,
               'name'           => 'Nicholas Hutabarat',
                'email'          => 'ifs21035@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 124,
               'name'           => 'Fernando Pakpahan',
                'email'          => 'ifs21036@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 125,
               'name'           => 'Emely Angelica Lestari',
                'email'          => 'ifs21052@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 126,
               'name'           => 'Desi Anju Nadetha Pakpahan',
                'email'          => 'mrs21022@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 127,
               'name'           => 'David Robetson',
                'email'          => 'mrs21030@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 128,
               'name'           => 'Gladys Silvana Sinaga',
                'email'          => 'mrs21019@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 129,
               'name'           => 'Aprilan Sisco Nababan',
                'email'          => 'mrs21007@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 130,
               'name'           => 'Irene Romauli Valentina Manalu',
                'email'          => 'bps21020@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 131,
               'name'           => 'Tunggul Hamonangan Malau',
                'email'          => 'bps21001@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 132,
               'name'           => 'Labora Roma Anugrah Simamora',
                'email'          => 'bps21028@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 133,
               'name'           => 'Batara G . Agung Simanungkalit',
                'email'          => 'els21002@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 134,
               'name'           => 'Neela Sartika Nababan',
                'email'          => 'els21003@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 135,
               'name'           => 'Nehemia Nico Aprinus Silitonga',
                'email'          => 'els21010@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 136,
               'name'           => 'JESSICA PASARIBU',
                'email'          => 'if322017@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 137,
               'name'           => 'JOI DIEGO NAPITUPULU',
                'email'          => 'if322034@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 138,
               'name'           => 'JOHANNA ROMAULI SIAGIAN',
                'email'          => '"	if322061@students.del.ac.id"',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 139,
               'name'           => 'ARTHUR GENIUS SORITUA PANJAITAN',
                'email'          => 'ce322022@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 140,
               'name'           => 'MORLIN APRILIZA SIAHAAN',
                'email'          => 'ce322053@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 141,
               'name'           => 'VERI MARSIL MARPAUNG',
                'email'          => 'if422014@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 142,
               'name'           => 'YESSI CHARISSA SIPAHUTAR',
                'email'          => 'if422058@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 143,
               'name'           => 'CALVIN JOSEP SILAEN',
                'email'          => 'if422038@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 144,
               'name'           => 'RUTH FIDIA SIREGAR',
                'email'          => 'ifs22050@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 145,
               'name'           => 'ICHA DARLENE HANNA SIPAHUTAR',
                'email'          => 'mrs22054@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 146,
               'name'           => 'RUHUT DANIELO PANJAITAN',
                'email'          => 'mrs22051@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 147,
               'name'           => 'ERLIN INTAN MANALU',
                'email'          => 'mrs22005@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 148,
               'name'           => 'MARIO AGUSTIN SIJABAT',
                'email'          => 'ifs22030@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 149,
               'name'           => 'YOHANA CHRISTINE SITANGGANG',
                'email'          => 'iss22050@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 150,
               'name'           => 'REINALDY HUTAPEA',
                'email'          => 'iss22010@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 151,
               'name'           => 'ROSARI SIMANJUNTAK',
                'email'          => 'iss22052@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 152,
               'name'           => 'ADE YOHANA AZEKA SIAHAAN',
                'email'          => 'bps22014@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 153,
               'name'           => 'TIOPAN ARI GABRIEL HUTAPEA',
                'email'          => 'bps22013@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 154,
               'name'           => 'EKO DAUD JUSUF HUTAPEA',
                'email'          => 'els22010@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 155,
               'name'           => 'EGITA ANANDITA BANJARNAHOR',
                'email'          => 'els22048@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 156,
               'name'           => 'FEBRINA ELISABETH SIHOMBING',
                'email'          => 'if323060@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 157,
               'name'           => 'INDRA AZIZ NUGRAHA',
                'email'          => 'if323030@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 158,
               'name'           => 'NATASYA DIAN ELENA SIAHAAN',
                'email'          => 'if323053@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 159,
               'name'           => 'DWI APRINO NAINGGOLAN',
                'email'          => 'ce323022@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 160,
               'name'           => 'JOSE RAFAEL LUMBAN RAJA',
                'email'          => 'ce323002@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 161,
               'name'           => 'VENESA HERAWATY HUTAJULU',
                'email'          => 'if423059@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 162,
               'name'           => 'BOAS WENDA',
                'email'          => 'if423073@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 163,
               'name'           => 'HANNA ADVENTI SINAGA',
                'email'          => 'mrs23021@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 164,
               'name'           => 'CITRA SOLAGRATIA LAM DEVI PARDOSI',
                'email'          => 'mrs23016@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 165,
               'name'           => 'JOY VALEDA SILALAHI',
                'email'          => 'iss23007@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 166,
               'name'           => 'TIFFANI RUMIRIS BR BUTAR-BUTAR',
                'email'          => 'iss23010@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 167,
               'name'           => 'ELIA YUDIKA HARIANJA',
                'email'          => 'bps23003@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 168,
               'name'           => 'SAMUEL YONATAN HUTAGALUNG',
                'email'          => 'bps23018@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 169,
               'name'           => 'BRANTLY GALLANT SITINJAK',
                'email'          => 'els23003@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 170,
               'name'           => 'WINNER JULIANTO PARDEDE',
                'email'          => 'els23008@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 171,
               'name'           => 'JAMES CHRISTIAN ARITONANG',
                'email'          => 'els23022@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 172,
               'name'           => 'SEPTIA NANCI YOVANKA MANULLANG',
                'email'          => 'bps23033@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 173,
               'name'           => 'ELIA YUDIKA HARIANJA',
                'email'          => 'tms23016@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 174,
               'name'           => 'SARIA LITA SIDAURUK',
                'email'          => 'tms23013@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 175,
               'name'           => 'ELIA YUDIKA HARIANJA',
                'email'          => 'bps23023@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 176,
               'name'           => 'DIMAS REXAN SAMUEL SIDABUTAR',
                'email'          => 'ifs24010@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 177,
               'name'           => 'CAHAYA RAYA SILAEN',
                'email'          => 'bps23053@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 178,
               'name'           => 'DANIEL MIKAEL NICOLAS SIANTURI',
                'email'          => 'ifs24037@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 179,
               'name'           => 'KEZIA VANIA PASARIBU',
                'email'          => 'iss24009@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 180,
               'name'           => 'JOICE ANASTASYA NAPITUPULU',
                'email'          => 'iss24020@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 181,
               'name'           => 'HIZKIA HANLEN CHOY SIHOMBING',
                'email'          => 'els24002@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 182,
               'name'           => 'IVAN JEREMIA DINATA HUTAJULU',
                'email'          => 'els24009@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 183,
               'name'           => 'AXELL FRITZ GALATIAN PANJAITAN',
                'email'          => 'mrs24001@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 184,
               'name'           => 'CLARA EKA SEPTIANA SORMIN',
                'email'          => 'mrs24015@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 185,
               'name'           => 'AGNES MARIA LUMBANTOBING',
                'email'          => 'mrs24060@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 186,
               'name'           => 'MARCELLO SAMUEL HUTAGALUNG',
                'email'          => 'tms24030@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 187,
               'name'           => 'IRA VALERIA TOGATOROP',
                'email'          => 'bps24022@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 188,
               'name'           => 'BINTANG JESISCA TANJUNG',
                'email'          => 'if424008@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 189,
               'name'           => 'BINSAR IMMANUEL SIREGAR',
                'email'          => 'if424038@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 190,
               'name'           => 'BRAHMANA PURBA',
                'email'          => 'if324002@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 191,
               'name'           => 'ANDREAS SUTAN SAHALA HUTAHAEAN',
                'email'          => 'ce324016@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],
            [
                'id'             => 192,
               'name'           => 'GRACE YESICA SIMANJUNTAK',
                'email'          => 'ce324054@students.del.ac.id',
                'password'       => bcrypt('12345678'),
                'remember_token' => null,
                'class_id'       => null,
            ],

        ];

        User::insert($users);
    }
}
